repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      # don't convert all strings to double-quotes
      args: [--skip-string-normalization]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: trailing-whitespace
      exclude: 'setup.cfg'  # bumpversion adds trailing whitespace for some reason. Fix if you know how to
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.670
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
