# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  configuration: docs/conf.py

# include pdf and epub
formats: all

python:
  version: 3.7
# Currently, install sections causes problem on readthedocs
# when running non-fresh-wiped build:
# FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-zoozityn/setup.py'
# Disable until figured out the reasons.
# For now we should not use sphinx-2.0 features!
#  install:
#    # pip will handle our pyproject.toml
#    - method: pip
#      path: .
#      extra_requirements:
#        - doc
