language: python
python:
  - 3.7
  - 3.6

before_script: pip install flit && flit install --deps production --extras test
script: py.test
#script: tox  # This will test against all supported architectures

jobs:
  include:
    - stage: deploy
      if: |
        repo = equeumco/happyly \
        AND tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/ \
        AND env(FLIT_PASSWORD) IS present
      script: flit publish
      python: 3.7
