# This is a configuration for buildbot-travis,
# a travis-like layer around buildbot.

language: python
python:
  - 3.7
  - 3.6

jobs:
  include:
    - stage: install
      script: pip install flit && flit install --deps production --extras test
    - stage: test
      #script: tox  # This will test against all supported architectures
      script: py.test
    - stage: deploy
      if: |
        repo = equeumco/happyly \
        AND tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/ \
        AND env(FLIT_PASSWORD) IS present
      script: flit publish

stages:
  - install
  - test
  - deploy
