dist: xenial  # for py37
language: python
python:
  - 3.6
  - 3.7
#  - 3.8-dev

install:
  - pip install flit
  - flit install --deps production --extras test,dev
script:
  # make sure pre-commit hooks are not broken
  - pre-commit run --all-files
  # and run tests
  - py.test

jobs:
  include:
    - stage: deploy
      if: |
        repo = equeumco/happyly \
        AND tag =~ /^v[0-9]+\.[0-9]+\.[0-9alphrc]+$/ \
        AND env(FLIT_PASSWORD) IS present
      env: FLIT_INDEX_URL=https://test.pypi.org/legacy/
      script: flit publish
      python: 3.7

#matrix:
#  allow_failures:
#    - python: 3.8-dev
